### ISSUE TITLE
No reversal of bytes for little endian Strings

### ISSUE THREAD

**Issue by camdenorrb** [nickrobson/nbt#1]
The writeString method lacks the reversal of the byte array, this caused a conflict with the NBT library I am building so just wanted to give you a heads up <3

**Comment by nickrobson** [comment]
Hey there @camdenorrb, thanks for taking the time to reach out. :) 

The byte array in the NBT string tag shouldn't be reversed for little endian (only the short tag describing the string length should be), as endianness only defines the byte order within what's considered a "word", which is the known number of bytes that make up a character. In UTF-8, which uses a streaming model so the computer always has to read one byte at a time, the byte order is fixed and identical for both little endian and big endian.

If this is causing a conflict where your library is reversing strings for little endian, then I believe that's a bug in your code sorry 😅 You can confirm this with other nbt libraries out there such as PyNBT, or load up a little endian nbt file in this and a web nbt explorer.

**Comment by camdenorrb** [comment]
Oh alright, thank you! :3
